spring:
  data:
    mongodb:
      host: hust-assistant-mongodb-container
      port: 27017
      database: hust_assistant
      username: root
      password: tla-hust!2026
      authentication-database: admin
  application:
    name: chat-session-service
  datasource:
    url: jdbc:mysql://hust-assistant-mysql-container:3306/hust_assistant
    username: root
    password: tla-hust!2026
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8085

application:
  service:
    chat-service:
      url: http://hust-assistant-chat-service:1923

eureka:
  client:
    service-url:
      defaultZone: http://hust-assistant-eureka-server:8671/eureka/
