spring:
  application:
    name: chat-session-service
  data:
    mongodb:
      host: localhost
      port: 27018
      database: hust_assistant
      username: root
      password: tla-hust!2026
      authentication-database: admin
  datasource:
    url: jdbc:mysql://localhost:3309/hust_assistant
    username: root
    password: tla-hust!2026
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8085

application:
  service:
    chat-service:
      url: http://localhost:1923

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/