eureka:
  client:
    service-url:
      defaultZone: http://hust-assistant-eureka-server:8671/eureka/

server:
  port: 8085
spring:
  application:
    name: crawler-service
  datasource:
    url: jdbc:mysql://hust-assistant-mysql-container:3306/hust_assistant
    username: root
    password: root
